import paramiko, sys, time
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
rp = paramiko.SSHClient()
rp.set_missing_host_key_policy(paramiko.AutoAddPolicy())
rp.connect('192.168.1.27', 22, 'tetasco1', 'saumata1192', timeout=10)
print('Monitoring 3 menit...')
time.sleep(180)
i,o,e = rp.exec_command('grep -iE "CamPush|broken|reconnect|terhubung" /tmp/tetasco_backend.log | grep -E "19:4|19:39" | tail -20')
result = o.read().decode('utf-8','replace').strip()
print(result or '✅ Tidak ada error — koneksi STABIL 3 menit penuh!')
rp.close()
